using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace StrongId.SourceGenerators.Tests;

public class StrongIdSourceGeneratorTests
{
    [Fact]
    public void GenerateStrongId()
    {
        string input =
            """
            namespace StrongId.Attributes
            {
                [AttributeUsage(AttributeTargets.Class)]
                public class StrongIdAttribute : Attribute
                {
                    /// <summary>
                    /// The Type of the identifier (defaults to System.Guid)
                    /// </summary>
                    public Type ParameterType { get; set; } = typeof(Guid);
                
                    /// <summary>
                    /// The property name in the marked class (defaults to "Id")
                    /// </summary>
                    public string ParameterName { get; set; } = "Id";
                }
            }
            
            
            namespace StrongId.Sample;
            
            [StrongId.Attributes.StrongId]
            public partial class SampleEntity
            {
            }
            
            """;


        string expectedPartialOutput =
            $$"""
              // <auto-generated/>
              
              using System;
              
              namespace StrongId.Sample;
              
              partial class SampleEntity
              {
              {{'\t'}}public SampleEntityId Id { get; private set; }
              }
              
              """;


        string expectedStrongIdOutput =
            $$"""
              // <auto-generated/>
              
              using System;
              
              namespace StrongId.Sample;
              
              public readonly record struct SampleEntityId(System.Guid Value)
              {
              {{'\t'}}public static SampleEntityId Create(System.Guid id) => new SampleEntityId(id);
              }
              
              """;

        // Assign
        //var generator = new StrongIdSourceGenerator();
        var generator = new StrongIdIncrementalSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(StrongIdSourceGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(input) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });


        // Act
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var partialClass = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity.g.cs"));
        var strongIdRecord = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntityId.g.cs"));

        var text = partialClass.GetText().ToString();
        var textTwo = strongIdRecord.GetText().ToString();
        
        // Assert
        Assert.Equal(expectedPartialOutput, text,
            ignoreLineEndingDifferences: true);


        Assert.Equal(expectedStrongIdOutput, textTwo,
            ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void GenerateStronglyTypedId()
    {
        string input =
            """
            namespace StrongId.Attributes
            {
                [AttributeUsage(AttributeTargets.Class)]
                public class StrongIdAttribute : Attribute
                {
                    /// <summary>
                    /// The Type of the identifier (defaults to System.Guid)
                    /// </summary>
                    public Type ParameterType { get; set; } = typeof(Guid);
                
                    /// <summary>
                    /// The property name in the marked class (defaults to "Id")
                    /// </summary>
                    public string ParameterName { get; set; } = "Id";
                }
            }
            
            namespace StrongId.Sample;

            [StrongId.Attributes.StrongId(ParameterType = typeof(int))]
            public partial class SampleEntity
            {
            }
            """;


        string expectedPartialOutput =
            $$"""
            // <auto-generated/>
            
            using System;
            
            namespace StrongId.Sample;
            
            partial class SampleEntity
            {
            {{'\t'}}public SampleEntityId Id { get; private set; }
            }
            
            """;


        string expectedStrongIdOutput =
            $$"""
              // <auto-generated/>
              
              using System;
              
              namespace StrongId.Sample;
              
              public readonly record struct SampleEntityId(int Value)
              {
              {{'\t'}}public static SampleEntityId Create(int id) => new SampleEntityId(id);
              }
              
              """;

        // Assign
        var generator = new StrongIdIncrementalSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(StrongIdSourceGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(input) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });


        // Act
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var partialClass = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity.g.cs"));
        var strongIdRecord = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntityId.g.cs"));

        
        var text = partialClass.GetText().ToString();
        var textTwo = strongIdRecord.GetText().ToString();

        // Assert
        Assert.Equal(expectedPartialOutput, text,
            ignoreLineEndingDifferences: true);

        Assert.Equal(expectedStrongIdOutput, textTwo,
            ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void GenerateStronglyNamedId()
    {
        string input =
            """
            namespace StrongId.Attributes
            {
                [AttributeUsage(AttributeTargets.Class)]
                public class StrongIdAttribute : Attribute
                {
                    /// <summary>
                    /// The Type of the identifier (defaults to System.Guid)
                    /// </summary>
                    public Type ParameterType { get; set; } = typeof(Guid);
                
                    /// <summary>
                    /// The property name in the marked class (defaults to "Id")
                    /// </summary>
                    public string ParameterName { get; set; } = "Id";
                }
            }
            
            namespace StrongId.Sample;

            [StrongId.Attributes.StrongId(ParameterName = "Google")]
            public partial class SampleEntity
            {
            }
            """;


        string expectedPartialOutput =
            $$"""
            // <auto-generated/>
            
            using System;
            
            namespace StrongId.Sample;
            
            partial class SampleEntity
            {
            {{'\t'}}public SampleEntityId Google { get; private set; }
            }
            
            """;


        string expectedStrongIdOutput =
            $$"""
              // <auto-generated/>
              
              using System;
              
              namespace StrongId.Sample;
              
              public readonly record struct SampleEntityId(System.Guid Value)
              {
              {{'\t'}}public static SampleEntityId Create(System.Guid id) => new SampleEntityId(id);
              }
              
              """;

        // Assign
        var generator = new StrongIdIncrementalSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(StrongIdSourceGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(input) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });


        // Act
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var partialClass = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity.g.cs"));
        var strongIdRecord = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntityId.g.cs"));

        
        var text = partialClass.GetText().ToString();
        var textTwo = strongIdRecord.GetText().ToString();

        // Assert
        Assert.Equal(expectedPartialOutput, text,
            ignoreLineEndingDifferences: true);

        Assert.Equal(expectedStrongIdOutput, textTwo,
            ignoreLineEndingDifferences: true);
    }
    
}