using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace StrongId.Tests;

public class StrongIdSourceGeneratorTests
{
    [Fact]
    public void GenerateStrongId()
    {
        string input = $@"namespace StrongId.Sample;

[StrongId]
public partial class SampleEntity
{{
}}";


        string expectedPartialOutput = @"// <auto-generated/>

using SourceGenerated.Ids;

namespace StrongId.Sample;

public partial class SampleEntity
{
	public SampleEntityId Id { get; private set; }
}
";
        
        
        string expectedStrongIdOutput = @"// <auto-generated/>

namespace SourceGenerated.Ids;

public sealed record SampleEntityId
{
    private SampleEntityId(System.Guid id)
    {
        Value = id;
    }

    public System.Guid Value { get; init; }

    public static SampleEntityId Create(System.Guid id) => new SampleEntityId(id);
}
";
        
        // Assign
        var generator = new StrongIdSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(StrongIdSourceGeneratorTests), new[]{CSharpSyntaxTree.ParseText(input)},
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });
        
        
        // Act
        var runResult = driver.RunGenerators(compilation).GetRunResult();
        
        var partialClass = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity.g.cs"));
        var strongIdRecord = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntityId.g.cs"));
            
        
        
        // Assert
        Assert.Equal(expectedPartialOutput, partialClass.GetText().ToString(),
            ignoreLineEndingDifferences: true);
        
        Assert.Equal(expectedStrongIdOutput, strongIdRecord.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
    
    [Fact]
    public void GenerateStronglyTypedId()
    {
        string input = $@"namespace StrongId.Sample;


[StrongId(ParameterType = typeof(int))]
public partial class SampleEntity
{{
}}";


        string expectedPartialOutput = @"// <auto-generated/>

using SourceGenerated.Ids;

namespace StrongId.Sample;

public partial class SampleEntity
{
	public SampleEntityId Id { get; private set; }
}
";
        
        
        string expectedStrongIdOutput = @"// <auto-generated/>

namespace SourceGenerated.Ids;

public sealed record SampleEntityId
{
    private SampleEntityId(int id)
    {
        Value = id;
    }

    public int Value { get; init; }

    public static SampleEntityId Create(int id) => new SampleEntityId(id);
}
";
        
        // Assign
        var generator = new StrongIdSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(StrongIdSourceGeneratorTests), new[]{CSharpSyntaxTree.ParseText(input)},
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });
        
        
        // Act
        var runResult = driver.RunGenerators(compilation).GetRunResult();
        
        var partialClass = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity.g.cs"));
        var strongIdRecord = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntityId.g.cs"));
            
        
        
        // Assert
        Assert.Equal(expectedPartialOutput, partialClass.GetText().ToString(),
            ignoreLineEndingDifferences: true);
        
        Assert.Equal(expectedStrongIdOutput, strongIdRecord.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
    
    [Fact]
    public void GenerateStronglyNamedId()
    {
        string input = $@"namespace StrongId.Sample;


[StrongId(ParameterName = ""Google"")]
public partial class SampleEntity
{{
}}";


        string expectedPartialOutput = @"// <auto-generated/>

using SourceGenerated.Ids;

namespace StrongId.Sample;

public partial class SampleEntity
{
	public SampleEntityId Google { get; private set; }
}
";
        
        
        string expectedStrongIdOutput = @"// <auto-generated/>

namespace SourceGenerated.Ids;

public sealed record SampleEntityId
{
    private SampleEntityId(System.Guid id)
    {
        Value = id;
    }

    public System.Guid Value { get; init; }

    public static SampleEntityId Create(System.Guid id) => new SampleEntityId(id);
}
";
        
        // Assign
        var generator = new StrongIdSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(StrongIdSourceGeneratorTests), new[]{CSharpSyntaxTree.ParseText(input)},
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });
        
        
        // Act
        var runResult = driver.RunGenerators(compilation).GetRunResult();
        
        var partialClass = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity.g.cs"));
        var strongIdRecord = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntityId.g.cs"));
            
        
        
        // Assert
        Assert.Equal(expectedPartialOutput, partialClass.GetText().ToString(),
            ignoreLineEndingDifferences: true);
        
        Assert.Equal(expectedStrongIdOutput, strongIdRecord.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }


    [Fact]
    public void GenerateStrongIdClassWithinClass()
    {
        string input = $@"namespace StrongId.Sample;

[StrongId]
public partial class SampleEntity
{{
    [StrongId]
    public partial class SampleEntity2
    {{
    }}
}}";



        string expectedPartialOutput = $$"""
                                       // <auto-generated/>

                                       using SourceGenerated.Ids;

                                       namespace StrongId.Sample;

                                       public partial class SampleEntity
                                       {
                                       {{'\t'}}public SampleEntityId Id { get; private set; }
                                       }

                                       """;


        string expectedPartial2Output = $$"""
                                        // <auto-generated/>

                                        using SourceGenerated.Ids;

                                        namespace StrongId.Sample;

                                        public partial class SampleEntity
                                        {
                                        {{'\t'}}public partial class SampleEntity2
                                        {{'\t'}}{
                                        {{'\t'}}{{'\t'}}public SampleEntity2Id Id { get; private set; }
                                        {{'\t'}}}
                                        }

                                        """;


        // Assign
        var generator = new StrongIdSourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(StrongIdSourceGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(input) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });
        
        var runResult = driver.RunGenerators(compilation).GetRunResult();
        
        var partialClass = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity.g.cs"));
        var partial2Class = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("SampleEntity2.g.cs"));
        
        Assert.Equal(expectedPartialOutput, partialClass.GetText().ToString(),
            ignoreLineEndingDifferences: true);
        
        Assert.Equal(expectedPartial2Output, partial2Class.GetText().ToString(),
            ignoreLineEndingDifferences: true);
        
    }
}